// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNufRNZTsBc4T3XeOw6CG-Dk0E00KrDEw',
    appId: '1:205196280951:android:a666240dafe6de62a7b272',
    messagingSenderId: '205196280951',
    projectId: 'mojadel-baf28',
    storageBucket: 'mojadel-baf28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3AbFLtUNBHy2B8kXb4rSrKzhxpUUoLM',
    appId: '1:205196280951:ios:37f59f22144e2177a7b272',
    messagingSenderId: '205196280951',
    projectId: 'mojadel-baf28',
    storageBucket: 'mojadel-baf28.appspot.com',
    iosBundleId: 'com.example.mojadel2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrW5X152jXEsBCuTUy7WVEAGwRO76sfeY',
    appId: '1:205196280951:web:844a8db3e4369d3aa7b272',
    messagingSenderId: '205196280951',
    projectId: 'mojadel-baf28',
    authDomain: 'mojadel-baf28.firebaseapp.com',
    storageBucket: 'mojadel-baf28.appspot.com',
    measurementId: 'G-4T91EKKP8L',
  );
}
